# See https://pre-commit.com/ for usage and config
default_language_version:
  python: python3.10
repos:
- repo: local
  hooks:
  - id: Ruff
    name: Ruff
    stages: [pre-commit]
    language: system
    entry: bash -lc "uv run delfino ruff"
    pass_filenames: false
